name: gluster-solo-2bricks-steady

services:
  gluster-solo:
    build: .
    hostname: gluster-solo
    restart: unless-stopped
    environment:
      - MODE=brick
      - VOLNAME=gv0
      - VTYPE=replica
      - REPLICA=2
      - BRICK_PATHS=/bricks/brick1,/bricks/brick2
      - PEERS=
      - LOG_LEVEL=INFO
      - PEER_WAIT_SECS=0
    volumes:
      - /mnt/disk1/gluster/brick1:/bricks/brick1
      - /mnt/disk2/gluster/brick2:/bricks/brick2
      - ./state:/var/lib/glusterd
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x glusterd >/dev/null && gluster volume info gv0 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 20