
# Compose: Gluster **server** (nur Daemon). Auf JEDEM Storage-Host starten.
services:
  glusterd:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        UBUNTU_TAG: "22.04"     # Jammy bewährt; 24.04 optional
    image: ghcr.io/yourorg/glusterfs-server:22.04
    container_name: glusterd
    network_mode: host          # Ports sauber binden
    restart: unless-stopped
    volumes:
      - /etc/glusterfs:/etc/glusterfs
      - /var/lib/glusterd:/var/lib/glusterd
      - /var/log/glusterfs:/var/log/glusterfs
      # Bricks auf dem Host binden:
      - /data/brick1:/bricks/brick1
      # Konfiguration:
      - ./examples/config.server.yaml:/etc/gluster-container/config.yaml:ro
    environment:
      - TZ=Europe/Berlin
