services:
  gluster-solo:
    container_name: ${CONTAINER_NAME:-gluster-solo}
    build:
      context: .
      dockerfile: Dockerfile
    hostname: ${HOSTNAME_GLUSTER:-gluster-solo}
    environment:
      TZ: ${TZ:-UTC}
      UMASK: ${UMASK:-0022}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      VOLNAME: ${VOLNAME:-gv0}
      REPLICA: ${REPLICA:-2}
      TRANSPORT: ${TRANSPORT:-tcp}
      CREATE_VOLUME: ${CREATE_VOLUME:-1}
      ALLOW_FORCE_CREATE: ${ALLOW_FORCE_CREATE:-1}
      VOL_OPTS: ${VOL_OPTS:-performance.client-io-threads=on,cluster.quorum-type=auto}
      AUTH_ALLOW: ${AUTH_ALLOW:-10.0.0.0/8}
      NFS_DISABLE: ${NFS_DISABLE:-1}
    network_mode: host
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - ./data/glusterd:/var/lib/glusterd
      - ./data/logs:/var/log/glusterfs
      DATA_PORT_START: ${DATA_PORT_START:-49152}
      DATA_PORT_END: ${DATA_PORT_END:-60999}
      PRIVATE_IP: ${PRIVATE_IP:-}
