name: gluster-solo-2bricks-steady
services:
  gluster-solo:
    build: .
    hostname: ${HOSTNAME_GLUSTER}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - pgrep -x glusterd >/dev/null && gluster volume info gv0 >/dev/null 2>&1
      interval: 10s
      timeout: 5s
      retries: 20
    environment:
    - MODE=brick
    - VOLNAME=gv0
    - VTYPE=replica
    - REPLICA=2
    - BRICK_PATHS=/bricks/brick1,/bricks/brick2
    - PEERS=
    - LOG_LEVEL=INFO
    - PEER_WAIT_SECS=0
    extra_hosts:
    - gluster-solo:${PRIVATE_IP}
    ports:
    - ${PRIVATE_IP}:${MGMT_PORT1}:${MGMT_PORT1}/tcp
    - ${PRIVATE_IP}:${MGMT_PORT2}:${MGMT_PORT2}/tcp
    - ${PRIVATE_IP}:${DATA_PORT_START}-${DATA_PORT_END}:${DATA_PORT_START}-${DATA_PORT_END}/tcp
    volumes:
    - /mnt/disk1/gluster/brick1:/bricks/brick1
    - /mnt/disk2/gluster/brick2:/bricks/brick2
    - ./state:/var/lib/glusterd
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
