version: "3.9"
name: gluster-single-brick

services:
  gluster-single:
    build: .
    container_name: gluster-single
    hostname: gluster-single
    restart: unless-stopped
    cap_add: [ "SYS_ADMIN" ]
    security_opt: [ "apparmor:unconfined" ]
    environment:
      - MODE=init
      - VOLNAME=gv0
      - VTYPE=replica
      - REPLICA=1
      - BRICK_PATH=/bricks/brick1
      - ALLOW_EMPTY_STATE=1
    volumes:
      - ./data/single/brick1:/bricks/brick1
      - ./state/single:/var/lib/glusterd
    networks: [ gluster-net ]
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x glusterd >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 20

networks:
  gluster-net: {}
