services:
  gluster-solo:
    build:
      context: .
    image: docker_glusterfs-gluster-solo:local
    container_name: gluster-solo
    hostname: gluster-solo
    environment:
      # Leave BRICK_HOST empty to let the entrypoint resolve to the hostname
      HOSTNAME_GLUSTER: gluster-solo
      ADDRESS_FAMILY: inet
      DATA_PORT_START: "49152"
      MAX_PORT: "49251"
      VOLNAME: gv0
      REPLICA: "2"
      TRANSPORT: tcp
      NFS_DISABLE: "1"
      AUTH_ALLOW: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    # Map brick storage; adjust to your host paths if needed
    volumes:
      - bricks:/bricks
      - glusterd:/var/lib/glusterd
    networks:
      - gluster-net
    ports:
      - "24007:24007/tcp"
      - "24008:24008/tcp"
      - "49152-49251:49152-49251/tcp"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    ulimits:
      nofile: 65536

volumes:
  bricks: {}
  glusterd: {}

networks:
  gluster-net:
    driver: bridge
