services:
  glusterA:
    container_name: glusterA
    build: { context: ., dockerfile: Dockerfile }
    hostname: ${HOSTNAME_GLUSTER:-glusterA}
    environment:
      TZ: ${TZ:-UTC}
      UMASK: ${UMASK:-0022}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      CREATE_VOLUME: "0"
      BRICK_HOST: ${BRICK_HOST:?set BRICK_HOST to the node's hostname/IP}
      NFS_DISABLE: ${NFS_DISABLE:-1}
      PRIVATE_IP: ${PRIVATE_IP:-}
      MGMT_PORT1: ${MGMT_PORT1:-24007}
      MGMT_PORT2: ${MGMT_PORT2:-24008}
      DATA_PORT_START: ${DATA_PORT_START:-49152}
      DATA_PORT_END: ${DATA_PORT_END:-49251}
      MAX_PORT: ${MAX_PORT:-60999}
      ADDRESS_FAMILY: ${ADDRESS_FAMILY:-inet}
    networks: [gluster-net]
    ports:
      - "${PRIVATE_IP}:${MGMT_PORT1:-24007}:${MGMT_PORT1:-24007}/tcp"
      - "${PRIVATE_IP}:${MGMT_PORT2:-24008}:${MGMT_PORT2:-24008}/tcp"
      - "${PRIVATE_IP}:${DATA_PORT_START:-49152}-${DATA_PORT_END:-49251}:${DATA_PORT_START:-49152}-${DATA_PORT_END:-49251}/tcp"
    privileged: true
    cap_add: ["SYS_ADMIN"]
    security_opt: ["apparmor:unconfined"]
    devices: ["/dev/fuse:/dev/fuse"]
    volumes:
      - ${HOST_BRICK1:?set HOST_BRICK1 in .env}:/bricks/brick1:rw
      - ${HOST_BRICK2:?set HOST_BRICK2 in .env}:/bricks/brick2:rw
      - ./data/glusterd:/var/lib/glusterd
      - ./data/logs:/var/log/glusterfs
    healthcheck:
      test: ["CMD-SHELL", "gluster --mode=script volume list >/dev/null 2>&1"]
      interval: ${HC_INTERVAL:-10s}
      timeout: ${HC_TIMEOUT:-5s}
      retries: ${HC_RETRIES:-20}
      start_period: ${HC_START_PERIOD:-30s}
    restart: unless-stopped

  glusterB:
    container_name: glusterB
    build: { context: ., dockerfile: Dockerfile }
    hostname: glusterB
    environment:
      TZ: ${TZ:-UTC}
      UMASK: ${UMASK:-0022}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      CREATE_VOLUME: "0"
      BRICK_HOST: ${BRICK_HOST:?set BRICK_HOST to the node's hostname/IP}
      NFS_DISABLE: ${NFS_DISABLE:-1}
      PRIVATE_IP: ${PRIVATE_IP:-}
      MGMT_PORT1: ${MGMT_PORT1:-24007}
      MGMT_PORT2: ${MGMT_PORT2:-24008}
      DATA_PORT_START: ${DATA_PORT_START:-49152}
      DATA_PORT_END: ${DATA_PORT_END:-49251}
      MAX_PORT: ${MAX_PORT:-60999}
      ADDRESS_FAMILY: ${ADDRESS_FAMILY:-inet}
    networks: [gluster-net]
    ports:
      - "${PRIVATE_IP}:${MGMT_PORT1:-24007}:${MGMT_PORT1:-24007}/tcp"
      - "${PRIVATE_IP}:${MGMT_PORT2:-24008}:${MGMT_PORT2:-24008}/tcp"
      - "${PRIVATE_IP}:${DATA_PORT_START:-49152}-${DATA_PORT_END:-49251}:${DATA_PORT_START:-49152}-${DATA_PORT_END:-49251}/tcp"
    privileged: true
    cap_add: ["SYS_ADMIN"]
    security_opt: ["apparmor:unconfined"]
    devices: ["/dev/fuse:/dev/fuse"]
    volumes:
      - ${HOST_BRICK1:?set HOST_BRICK1 in .env}:/bricks/brick1:rw
      - ${HOST_BRICK2:?set HOST_BRICK2 in .env}:/bricks/brick2:rw
      - ./data/glusterd:/var/lib/glusterd
      - ./data/logs:/var/log/glusterfs
    healthcheck:
      test: ["CMD-SHELL", "gluster --mode=script volume list >/dev/null 2>&1"]
      interval: ${HC_INTERVAL:-10s}
      timeout: ${HC_TIMEOUT:-5s}
      retries: ${HC_RETRIES:-20}
      start_period: ${HC_START_PERIOD:-30s}
    restart: unless-stopped

  glusterC:
    container_name: glusterC
    build: { context: ., dockerfile: Dockerfile }
    hostname: glusterC
    environment:
      TZ: ${TZ:-UTC}
      UMASK: ${UMASK:-0022}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      CREATE_VOLUME: "0"
      BRICK_HOST: ${BRICK_HOST:?set BRICK_HOST to the node's hostname/IP}
      NFS_DISABLE: ${NFS_DISABLE:-1}
      PRIVATE_IP: ${PRIVATE_IP:-}
      MGMT_PORT1: ${MGMT_PORT1:-24007}
      MGMT_PORT2: ${MGMT_PORT2:-24008}
      DATA_PORT_START: ${DATA_PORT_START:-49152}
      DATA_PORT_END: ${DATA_PORT_END:-49251}
      MAX_PORT: ${MAX_PORT:-60999}
      ADDRESS_FAMILY: ${ADDRESS_FAMILY:-inet}
    networks: [gluster-net]
    ports:
      - "${PRIVATE_IP}:${MGMT_PORT1:-24007}:${MGMT_PORT1:-24007}/tcp"
      - "${PRIVATE_IP}:${MGMT_PORT2:-24008}:${MGMT_PORT2:-24008}/tcp"
      - "${PRIVATE_IP}:${DATA_PORT_START:-49152}-${DATA_PORT_END:-49251}:${DATA_PORT_START:-49152}-${DATA_PORT_END:-49251}/tcp"
    privileged: true
    cap_add: ["SYS_ADMIN"]
    security_opt: ["apparmor:unconfined"]
    devices: ["/dev/fuse:/dev/fuse"]
    volumes:
      - ${HOST_BRICK1:?set HOST_BRICK1 in .env}:/bricks/brick1:rw
      - ${HOST_BRICK2:?set HOST_BRICK2 in .env}:/bricks/brick2:rw
      - ./data/glusterd:/var/lib/glusterd
      - ./data/logs:/var/log/glusterfs
    healthcheck:
      test: ["CMD-SHELL", "gluster --mode=script volume list >/dev/null 2>&1"]
      interval: ${HC_INTERVAL:-10s}
      timeout: ${HC_TIMEOUT:-5s}
      retries: ${HC_RETRIES:-20}
      start_period: ${HC_START_PERIOD:-30s}
    restart: unless-stopped

networks:
  gluster-net:
    driver: bridge
