# Compose file for running a Gluster server node.
# Run this on each Gluster host; bind-mount all brick directories from the host.
# Use together with examples/config.server.yaml (or server-bootstrap for initial bring-up).
version: "3.9"
# Run this on each Gluster node host. Adjust host paths to your brick locations.
services:
  glusterd:
    build: .
    image: ghcr.io/yourorg/glusterfs-hybrid:ubuntu24
    container_name: glusterd
# Use host networking so Gluster ports bind correctly
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/glusterfs:/etc/glusterfs
      - /var/lib/glusterd:/var/lib/glusterd
      - /var/log/glusterfs:/var/log/glusterfs
      - /data/brick1:/bricks/brick1
      - ./examples/config.server.yaml:/etc/gluster-container/config.yaml:ro
    environment:
      - TZ=Europe/Berlin
    # Optional healthcheck uses scripts/healthcheck.sh baked into image
