services:
  glusterd:
    build:
      context: .
    image: ghcr.io/yourorg/glusterfs-hybrid:ubuntu22
    container_name: glusterd
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/mnt/data:rw
    cap_add:
      - SYS_ADMIN
    entrypoint: ["tini","--","/usr/local/bin/bootstrap.sh"]
    command: ["/etc/gluster-container/config.yaml","--role","server"]
    environment:
      TZ: Europe/Berlin
