version: "3.9"
name: gluster-brick-only

services:
  gluster-brick:
    build: .
    container_name: gluster-brick
    hostname: gluster-brick
    restart: unless-stopped
    environment:
      - MODE=brick
      - BRICK_PATH=/bricks/brick1
      - VOLNAME=auto
      - PEERS=
      - REQUIRE_ALL_PEERS=0
      - ADDRESS_FAMILY=inet
      - PORT_RANGE=49152-49251
      - LOG_LEVEL=WARNING
      - TRACE=0
      - PEER_WAIT_SECS=0
      - PEER_WAIT_INTERVAL=1
    volumes:
      - ./data/gluster1/brick1:/bricks/brick1
      - ./state/gluster1:/var/lib/glusterd
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks: [gluster-net]
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x glusterd >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 20

networks:
  gluster-net:
    name: gluster-net
