
# Compose: Gluster **client** (FUSE-Mount im Container, bind zurück auf Host).
services:
  gluster-client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        UBUNTU_TAG: "22.04"
    image: ghcr.io/yourorg/glusterfs-client:22.04
    container_name: gluster-client
    restart: unless-stopped
    # FUSE braucht SYS_ADMIN + /dev/fuse, je nach Host evtl. unconfined profiles
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    # Mount-Propagation, damit der FUSE-Mount im Host sichtbar wird:
    volumes:
      - type: bind
        source: /mnt/gluster
        target: /mnt/gluster
        bind:
          propagation: rshared
      - ./examples/config.client.yaml:/etc/gluster-container/config.yaml:ro
    environment:
      - TZ=Europe/Berlin
