name: gluster-solo-2bricks
services:
  gluster-solo:
    build: .
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME_GLUSTER}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-lc", "gluster volume info >/dev/null 2>&1"]
      interval: ${HC_INTERVAL}
      timeout: ${HC_TIMEOUT}
      retries: ${HC_RETRIES}
    ports:
      - "${MGMT_PORT1}:${MGMT_PORT1}/tcp"
      - "${MGMT_PORT2}:${MGMT_PORT2}/tcp"
      - "${DATA_PORT_START}-${DATA_PORT_END}:${DATA_PORT_START}-${DATA_PORT_END}/tcp"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
env_file:
  - .envvolumes:
      - glusterd:/var/lib/glusterd
    networks:
      - gluster-net
networks:
  gluster-net: {}
volumes:
  glusterd: {}
