# examples/config.client.yaml
# Client: mount a Gluster volume into /mnt/glusterFS INSIDE the container;
# thanks to mount propagation (rshared), the mount will appear on the host at the
# same path for as long as the container runs.
role: "client"
mounts:
  - remote: "gfs1:/gv0"
    target: "/mnt/glusterFS"
    opts: "backupvolfile-server=gfs2,_netdev,log-level=INFO"
