# === [DOC] Autogenerierte Inline-Dokumentation: compose.solo-2bricks-replica.yml ===
# Datei: compose/compose.solo-2bricks-replica.yml
# Typ: YAML (Compose/Volumes/Beispiele).
# Zweck: Deklarative Konfiguration (Container-Stack, Volume-Spezifikationen).
# Hinweis: Kommentare erläutern Felder, sinnvolle Defaults und Sicherheitsüberlegungen.
# === [DOC-END] ===

version: '3.9'
services:
  gluster-solo:
    container_name: ${CONTAINER_NAME:-gluster-solo}
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: host
    hostname: ${HOSTNAME_GLUSTER:-gluster-solo}
    environment:
      MODE: ${MODE:-solo}
      ADDRESS_FAMILY: ${ADDRESS_FAMILY:-inet}
      DATA_PORT_START: ${DATA_PORT_START:-49152}
      DATA_PORT_END: ${DATA_PORT_END:-49251}
      VOL_BOOTSTRAP: true
      VOLUMES_YAML: /etc/gluster/volumes.yml
      PRIVATE_IP: ${PRIVATE_IP:-}
      MGMT_PORT1: ${MGMT_PORT1:-24007}
      MGMT_PORT2: ${MGMT_PORT2:-24008}
      test:
      - CMD-SHELL
      - gluster --mode=script volume list >/dev/null 2>&1
      interval: ${HC_INTERVAL:-10s}
      timeout: ${HC_TIMEOUT:-5s}
      retries: ${HC_RETRIES:-20}
      start_period: ${HC_START_PERIOD:-60s}
    restart: unless-stopped
networks:
  gluster-net:
    driver: bridge
