# docker-compose.yml
services:
  gluster1:
    image: drezael/glusterfs:0.1
    container_name: gluster1
    hostname: gluster1
    restart: unless-stopped

    # Für trusted.*-xattrs auf den Bricks (sonst EPERM):
    privileged: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

    environment:
      - TZ=Europe/Berlin
      - AUTO_PROBE_PEERS=true
      - AUTO_CREATE_VOLUMES=true
      - ALLOW_SINGLE_BRICK=false
      - REWRITE_LOCAL_BRICKS_TO=127.0.0.1
      # optional:
      # - VOL_NAME=gv0
      # - PEERS=gluster1,gluster2

    volumes:
      - /srv/gluster:/gluster
      - /data/gluster/vol1_brick:/gluster/bricks/vol1/brick
      - /data/gluster/vol2_brick:/gluster/bricks/vol2/brick

    ports:
      - "24007:24007"
      - "24008:24008"
      - "49152-49251:49152-49251"
